apiVersion: apps/v1
kind: Deployment
metadata:
  name: funeralpython
  labels:
    app: funeralpython
spec:
  replicas: 1
  selector:
    matchLabels:
      app: funeralpython
  template:
    metadata:
      labels:
        app: funeralpython
    spec:
      containers:
        - name: funeralpython
          image: "username/funeralpython:latest"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
