# funerallinfopoc/kubernetes/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: api-keys
type: Opaque
data:
  OPENAI_API_KEY: c2stcHJvai1jNXhTYUVMZFdFVWljaGYtODR5REVlYlN4c3RURXY0OWVYOU14cmVMNFFMcTZWT09UeVEzN2U0ZlhnTl9feUFueGRxZ3lHeXFodVQzQmxia0ZKWWlkaWVWQ2NuS1lZWkhlanRiLTN3ZjNDVC1KMXdud3c4V3hUOV9tVGtCZ0p0ZERtSzAwR0p4S0N6OGhSSWNNUmlBcmVkTEFSa0E=
  AZURE_STORAGE_CONNECTION_STRING: RGVmYXVsdEVuZHBvaW50c1Byb3RvY29sPWh0dHBzO0FjY291bnROYW1lPWEwNzEwOThibG9idGVzdDtBY2NvdW50S2V5PUt0WndJMzdRaUE2SnJQaFRqaEN2cWFFZC9wYWY2aXdCS3NBcTVqYi9tYUlNeEtwaFF1cldpSkRUejVrTmtWTmMwd0QvSXovOEZHeFUrQVN0MkkvU0xBPT07RW5kcG9pbnRTdWZmaXg9Y29yZS53aW5kb3dzLm5ldA==